### ISSUE TITLE
revisit working name: STAREmaster

### ISSUE THREAD

**Issue by captainkirk99** [captainkirk99/STAREmaster#4]
I'm not married to it. It was just the first thing I thought of. Let me know if it should change.

**Comment by captainkirk99** [comment]
In document 2020-0415-CompanionFileSpecifications-1, @michaelleerilee seems to suggest the name "stash".

Or perhaps we should go with something more descriptive, like "create_stare_indicies".

**Comment by michaelleerilee** [comment]
STARE_stash is a small class declared in STARE.h.in for reading and writing STARE index vectors to/from binary files.

Index creation is generally with methods of STARE with names including ValueFrom...

**Comment by captainkirk99** [comment]
OK, James likes STAREmaster so we will stick with it.
